-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgDZWUtw3G5EkgJ2BkvjVfqJDEThp5LvG1gUsbconjD3+gCgYIKoZIzj0DAQehRANCAATROJbkOFrVvc4sIn+XWbCDFrlcwAd0jZWDkHC+NGIkup+srOaJBukVxUzZZKVHLRAV0eeKxKq4T3dQic/iT47e
-----END PRIVATE KEY-----